name: Build Geode Mod

on:
  push:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build git

      - name: Clone Geode SDK
        run: |
          git clone https://github.com/geode-sdk/geode.git

      - name: Configure
        run: |
          cmake -B build -G Ninja

      - name: Build
        run: |
          cmake --build build

      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: geode-mod
          path: build/*.geode
